# IMPORTANT NOTE:
# This docker-compose configuration is only for 
# and Braven Help.  Start it using: 
# dinghy up
# cp -a ./osqa/docker-compose/config/settings_local.py ./osqa/settings_local.py
# docker-compose -f ./docker-compose-osqa.yml build
# cd osqa
# cat docker-compose/config/braven_settings.sql | docker-compose -f ../docker-compose-osqa.yml run --rm helpweb psql -h helpdb -U root -d osqa
# cd ..
# docker-compose -f ./docker-compose-osqa.yml up -d
#

#######################
###  OSQA (aka Braven Help)
#######################
helpweb:
  build: ./osqa
  command: /app/docker-compose/scripts/run.bat
  volumes:
    - "./osqa:/app"
  links:
    - helpdb
  ports:
    - "3006:3006"
  environment:
    VIRTUAL_HOST: help.docker
    VIRTUAL_PORT: 3006

helpdb:
  image: postgres:9.3
  environment:
    POSTGRES_DB: osqa
    POSTGRES_USER: root

